# Generated by Django 3.2.4 on 2021-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('student_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=32)),
            ],
        ),
    ]
