# Generated by Django 3.2.4 on 2021-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolding', '0002_coursedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='status',
            field=models.CharField(default='INCOMPLETE', max_length=32),
        ),
    ]
