# Generated by Django 3.2.7 on 2021-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolding', '0004_alter_coursedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='certificate',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
