# Generated by Django 3.2.7 on 2021-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolding', '0005_coursedetails_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
