# Generated by Django 3.2.4 on 2021-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_alter_certificate_grade_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='studentId',
            field=models.CharField(default=112, max_length=32),
            preserve_default=False,
        ),
    ]
