# Generated by Django 3.2.4 on 2021-10-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_certificate_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
