# Generated by Django 3.2.4 on 2021-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_certificate_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='estimated_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payment_details',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
