# Generated by Django 3.2.7 on 2021-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_auto_20211020_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='estimated_fee',
            field=models.BigIntegerField(null=True),
        ),
    ]
